import { randomUUID } from 'node:crypto'

import type { FhirClient } from '#core/fhir/client'
import type { RecordedResponse } from '#core/http/smart-http-client'
import type { LaunchContext } from '#core/smart/types'
import { hl7Refs, navRefs } from '#validation/common-refs'
import {
    runProbes,
    skipped,
    type ProbeContext,
    type ProbeOutcome,
    type ResourceProbe,
} from '#validation/fhir/probe'
import { parseScope } from '#validation/smart/scopes'
import { validation, type Validation } from '#validation/validation'
import type { Binary, Bundle, DocumentReference, OperationOutcome, QuestionnaireResponse } from 'fhir/r4'

import { validateBinary } from './resources/binary'
import {
    REQUIRED_BATCH_BUNDLE_TYPE,
    validateBatchBundleRequest,
    validateBatchBundleResponse,
} from './resources/bundle'
import {
    SYKMELDING_DOCUMENT_TYPE_CODE,
    SYKMELDING_DOCUMENT_TYPE_SYSTEM,
    validateDocumentReference,
} from './resources/document-reference'
import {
    SYKMELDING_QUESTIONNAIRE_CANONICAL_URL,
    validateQuestionnaireResponse,
} from './resources/questionnaire-response'

/**
 * Write probes are the only probes that mutate the vendor's EHR: every successful run leaves a
 * test resource behind, and each probe's findings name the resource and id so the vendor can
 * delete it afterwards.
 *
 * Nav's real write-back (`bundle.md` / ADR01) uses `PUT /<type>/<sykmelding-id>` with a
 * client-assigned id so a retried write is idempotent — resending the same PUT must not file the
 * sykmelding twice in the patient's journal. The DocumentReference and QuestionnaireResponse
 * probes therefore issue the same PUT twice and assert the id does not change. Binary is written
 * with `POST` (server-assigned id) instead, since Nav never needs it reachable by a chosen id.
 */

const TEST_PDF_CONTENT =
    '%PDF-1.4\n% Minimal placeholder document generated by the Nav SMART on FHIR validator.\n'
const TEST_PDF_BASE64 = Buffer.from(TEST_PDF_CONTENT).toString('base64')
const TEST_PDF_BYTES = Buffer.from(TEST_PDF_CONTENT)

function testId(kind: string): string {
    return `smart-on-fhir-validator-${kind}-${randomUUID()}`
}

function grantedScopesText(launch: LaunchContext): string {
    return launch.grantedScopes.length > 0 ? launch.grantedScopes.join(', ') : 'none'
}

/**
 * A granted scope permits writing `resourceType` when it is a clinical scope for that resource
 * (or `*`) whose CRUDS permission includes create, update or delete. Both SMART v1 (`write`) and
 * v2 (`cud`/`cruds`) forms are accepted, since EHRs may grant either.
 */
function grantsWriteScope(launch: LaunchContext, resourceType: string): boolean {
    return launch.grantedScopes.some((raw) => {
        const scope = parseScope(raw)
        if (scope.kind !== 'clinical') return false
        if (scope.resource !== '*' && scope.resource !== resourceType) return false
        return /[cud]/.test(scope.cruds)
    })
}

function asRecord(body: unknown): Record<string, unknown> | null {
    return body != null && typeof body === 'object' ? (body as Record<string, unknown>) : null
}

function asTyped<T extends { resourceType: string }>(
    body: unknown,
    resourceType: T['resourceType'],
): T | null {
    const record = asRecord(body)
    return record?.resourceType === resourceType ? (record as unknown as T) : null
}

function operationOutcomeSummary(body: unknown): string | null {
    const outcome = asTyped<OperationOutcome>(body, 'OperationOutcome')
    if (!outcome?.issue) return null
    return outcome.issue.map((issue) => issue.diagnostics ?? issue.details?.text ?? issue.code).join('; ')
}

function extractCreatedId(response: RecordedResponse): string | null {
    const bodyId = asRecord(response.body)?.id
    if (typeof bodyId === 'string' && bodyId.length > 0) return bodyId

    const location = response.headers.get('Location') ?? response.headers.get('Content-Location')
    if (!location) return null

    const match = /\/([^/?]+?)(?:\/_history\/[^/?]+)?\/?(?:\?.*)?$/.exec(location)
    return match?.[1] ?? null
}

function createOutcomeValidations(response: RecordedResponse, resourceType: string): Validation[] {
    const validations: Validation[] = []
    const url = response.exchange.request.url

    if (response.status === 201) {
        validations.push(validation(`POST ${url} correctly returned 201 Created`, 'OK'))
    } else if (response.status === 200) {
        validations.push(
            validation(
                `POST ${url} returned 200 OK instead of 201 Created for a new ${resourceType}. FHIR R4 requires a successful create to return 201.`,
                'WARNING',
                [hl7Refs.fhirHttpCreate],
            ),
        )
    } else {
        const outcomeSummary = operationOutcomeSummary(response.body)
        const transport =
            response.status === 0 ? ` (transport failure: ${response.exchange.error ?? 'unknown'})` : ''
        validations.push(
            validation(
                `POST ${url} failed to create the ${resourceType} with status ${response.status}${transport}. ${outcomeSummary ? `Server returned: ${outcomeSummary}` : 'No OperationOutcome was returned to explain the failure.'}`,
                'ERROR',
                [hl7Refs.fhirHttpCreate],
            ),
        )
        return validations
    }

    const location = response.headers.get('Location') ?? response.headers.get('Content-Location')
    if (!location) {
        validations.push(
            validation(
                `POST ${url} did not include a Location or Content-Location header pointing at the created ${resourceType}`,
                'WARNING',
                [hl7Refs.fhirHttpCreate],
            ),
        )
    } else {
        validations.push(validation(`Response included a Location header: "${location}"`, 'OK'))
    }

    return validations
}

/**
 * FHIR R4 permits either 201 or 200 for a `PUT` update-as-create, so neither is a WARNING, and no
 * `Location` header is required since the client chose the URL.
 *
 * @see https://hl7.org/fhir/R4/http.html#upsert
 */
function upsertOutcomeValidations(
    response: RecordedResponse,
    resourceType: string,
    attempt: 'first' | 'second',
): Validation[] {
    const url = response.exchange.request.url
    const attemptLabel = attempt === 'first' ? 'First' : 'Second'

    if (response.status === 201) {
        if (attempt === 'first') {
            return [
                validation(
                    `${attemptLabel} PUT ${url} returned 201 Created, a legal update-as-create response per FHIR R4.`,
                    'OK',
                    [hl7Refs.fhirHttpUpsert],
                ),
            ]
        }

        return [
            validation(
                `${attemptLabel} PUT ${url} (same client-assigned id, repeated) returned 201 Created again. Per FHIR R4 upsert semantics, a repeated PUT to an id that already exists should return 200 OK; returning 201 a second time may mean the server created a second, distinct resource instead of updating the first, which risks the sykmelding being filed twice in the patient's journal.`,
                'WARNING',
                [hl7Refs.fhirHttpUpsert, navRefs.adr01],
            ),
        ]
    }

    if (response.status === 200) {
        return [
            validation(
                `${attemptLabel} PUT ${url} returned 200 OK, a legal update-as-create response per FHIR R4.`,
                'OK',
                [hl7Refs.fhirHttpUpsert],
            ),
        ]
    }

    const outcomeSummary = operationOutcomeSummary(response.body)
    const transport =
        response.status === 0 ? ` (transport failure: ${response.exchange.error ?? 'unknown'})` : ''
    return [
        validation(
            `${attemptLabel} PUT ${url} failed to upsert the ${resourceType} with status ${response.status}${transport}. ${outcomeSummary ? `Server returned: ${outcomeSummary}` : 'No OperationOutcome was returned to explain the failure.'}`,
            'ERROR',
            [hl7Refs.fhirHttpUpsert],
        ),
    ]
}

/**
 * Nav's write-back relies on a second PUT of the same client-assigned id being an update rather
 * than a second create, so a retry cannot double-file a sykmelding in the patient's journal.
 */
function idempotencyValidation(
    first: RecordedResponse,
    second: RecordedResponse,
    resourceType: string,
    id: string,
): Validation {
    const firstId = asRecord(first.body)?.id
    const secondId = asRecord(second.body)?.id
    const firstMatches = firstId === undefined || firstId === id
    const secondMatches = secondId === undefined || secondId === id

    if (firstMatches && secondMatches) {
        return validation(
            `Repeating PUT ${second.exchange.request.url} with the same client-assigned id "${id}" did not produce a different resource id: both responses are consistent with a single ${resourceType}/${id}. This is the idempotency property Nav's write-back depends on (ADR01): a retried write after a network blip must not double-file the sykmelding.`,
            'OK',
            [navRefs.adr01],
        )
    }

    return validation(
        `Repeating PUT ${second.exchange.request.url} with the same client-assigned id "${id}" produced a different resource id (first response id: "${String(firstId)}", second response id: "${String(secondId)}"). A compliant PUT-as-upsert must always operate on ${resourceType}/${id}; returning a different id risks the sykmelding being filed twice in the patient's journal.`,
        'ERROR',
        [hl7Refs.fhirHttpUpsert, navRefs.adr01],
    )
}

/**
 * A 403 is the correct outcome when the write scope was never granted: an EHR that rejects an
 * unauthorised write is conformant, not failing.
 */
function scopeEnforcementOutcome(
    probe: ResourceProbe,
    response: RecordedResponse,
    resourceType: string,
    launch: LaunchContext,
    method: string = 'POST',
): ProbeOutcome {
    const url = response.exchange.request.url
    const validations: Validation[] = []

    if (response.status === 403) {
        validations.push(
            validation(
                `No write scope for ${resourceType} was granted (granted scopes: ${grantedScopesText(launch)}). ${method} ${url} was correctly rejected with 403 Forbidden. This is the expected behaviour for a write attempted outside the granted scopes.`,
                'OK',
                [hl7Refs.smartLaunch],
            ),
        )
    } else if (response.ok) {
        validations.push(
            validation(
                `No write scope for ${resourceType} was granted (granted scopes: ${grantedScopesText(launch)}), yet ${method} ${url} succeeded with status ${response.status}. A SMART-conformant server must enforce granted scopes and reject writes outside them with 403 Forbidden.`,
                'ERROR',
                [hl7Refs.smartLaunch],
            ),
        )
    } else {
        validations.push(
            validation(
                `No write scope for ${resourceType} was granted (granted scopes: ${grantedScopesText(launch)}). ${method} ${url} was rejected with status ${response.status} rather than 403 Forbidden. 403 is the status a SMART server should use to signal insufficient authorization for an otherwise well-formed request.`,
                'WARNING',
                [hl7Refs.smartLaunch],
            ),
        )
    }

    return { probeId: probe.id, label: probe.label, exchangeId: response.exchange.id, validations }
}

function testResourceNotice(resourceType: string, id: string): Validation {
    return validation(
        `Created a test ${resourceType} in the vendor's EHR with id "${id}". This is a real record written to their system by this validator. Delete or clean up "${resourceType}/${id}" after reviewing this report.`,
        'INFO',
    )
}

function containsResource(bundle: Bundle | null, resourceType: string, id: string): boolean {
    if (bundle == null) return false
    return (bundle.entry ?? []).some((entry) => {
        const resource = entry.resource as { resourceType?: string; id?: string } | undefined
        return resource?.resourceType === resourceType && resource.id === id
    })
}

/** Verifies `resourceType` can be found from launch context alone, without configured ids. */
async function searchableValidations(
    context: ProbeContext,
    resourceType: string,
    createdId: string,
    params: Record<string, string>,
    paramDescription: string,
): Promise<Validation[]> {
    const response = await context.fhir.search(resourceType, params)
    const url = response.exchange.request.url
    const validations: Validation[] = []

    if (!response.ok) {
        validations.push(
            validation(
                `GET ${url} failed with status ${response.status}. A written ${resourceType} must be findable by ${paramDescription} alone.`,
                'ERROR',
                [hl7Refs.fhirHttpSearch],
            ),
        )
        return validations
    }

    const bundle = asTyped<Bundle>(response.body, 'Bundle')
    if (bundle == null) {
        validations.push(
            validation(`GET ${url} did not return a FHIR Bundle`, 'ERROR', [hl7Refs.fhirHttpSearch]),
        )
        return validations
    }

    if (bundle.type !== 'searchset') {
        validations.push(
            validation(
                `GET ${url} returned a Bundle of type "${bundle.type}", expected "searchset"`,
                'ERROR',
                [hl7Refs.search],
            ),
        )
    }

    if (containsResource(bundle, resourceType, createdId)) {
        validations.push(
            validation(
                `The created ${resourceType} was found via GET ${url} (searchable by ${paramDescription})`,
                'OK',
            ),
        )
    } else {
        validations.push(
            validation(
                `The created ${resourceType} ("${resourceType}/${createdId}") was NOT found via GET ${url}. It must be discoverable by ${paramDescription} alone so it can be located without a server-assigned id.`,
                'ERROR',
                [hl7Refs.documentReference],
            ),
        )
    }

    return validations
}

/**
 * Runs one Binary upload mechanism (FHIR-JSON or raw body) through the same create-then-read-back
 * checks. Reports `succeeded: false` when the mechanism cannot be verified end-to-end, so the
 * caller can decide whether the other mechanism covers Nav's "Må" requirement for Binary.
 */
async function binaryMechanismValidations(
    fhir: FhirClient,
    response: RecordedResponse,
    mechanismLabel: string,
): Promise<{ validations: Validation[]; succeeded: boolean }> {
    const validations = createOutcomeValidations(response, 'Binary')

    if (!response.ok) {
        return { validations, succeeded: false }
    }

    const createdId = extractCreatedId(response)
    if (createdId == null) {
        validations.push(
            validation(
                `Could not determine the id of the Binary created via the ${mechanismLabel} mechanism from the response body or Location header, so round-trip could not be verified.`,
                'ERROR',
                [hl7Refs.binary],
            ),
        )
        return { validations, succeeded: false }
    }

    validations.push(testResourceNotice('Binary', createdId))
    validations.push(validation(`Binary upload via the ${mechanismLabel} mechanism succeeded.`, 'OK'))

    const created = asTyped<Binary>(response.body, 'Binary')
    if (created) {
        validations.push(...validateBinary(created, { id: createdId, contentType: 'application/pdf' }))
    }

    const readBack = await fhir.read('Binary', createdId)
    if (!readBack.ok) {
        validations.push(
            validation(
                `GET ${readBack.exchange.request.url} (round-trip read-back for the ${mechanismLabel} upload) failed with status ${readBack.status}.`,
                'ERROR',
                [hl7Refs.binary],
            ),
        )
        return { validations, succeeded: false }
    }

    validations.push(
        validation(
            `Round-trip read-back succeeded for the ${mechanismLabel} upload: GET ${readBack.exchange.request.url} returned 200 OK`,
            'OK',
        ),
    )
    const readBackTyped = asTyped<Binary>(readBack.body, 'Binary')
    if (readBackTyped) {
        validations.push(...validateBinary(readBackTyped, { id: createdId, contentType: 'application/pdf' }))
    }

    return { validations, succeeded: true }
}

function buildInlineDocumentReference(launch: LaunchContext): DocumentReference {
    return {
        resourceType: 'DocumentReference',
        status: 'current',
        type: {
            coding: [
                {
                    system: SYKMELDING_DOCUMENT_TYPE_SYSTEM,
                    code: SYKMELDING_DOCUMENT_TYPE_CODE,
                    display: 'Sykmeldinger og trygdesaker',
                },
            ],
        },
        subject: { reference: `Patient/${launch.patientId}` },
        author: launch.practitionerId ? [{ reference: `Practitioner/${launch.practitionerId}` }] : undefined,
        date: new Date().toISOString(),
        description: 'Sykmelding write-back test document from the Nav SMART on FHIR validator',
        content: [
            {
                attachment: {
                    title: 'Sykmelding (test)',
                    language: 'NO-nb',
                    contentType: 'application/pdf',
                    data: TEST_PDF_BASE64,
                },
            },
        ],
        context: {
            encounter: [{ reference: `Encounter/${launch.encounterId}` }],
        },
    }
}

function buildBinary(): Binary {
    return { resourceType: 'Binary', contentType: 'application/pdf', data: TEST_PDF_BASE64 }
}

function buildDocumentReferenceForBinary(launch: LaunchContext, binaryId: string): DocumentReference {
    const doc = buildInlineDocumentReference(launch)
    return {
        ...doc,
        content: [
            {
                attachment: {
                    title: 'Sykmelding (test, Binary reference)',
                    language: 'NO-nb',
                    contentType: 'application/pdf',
                    url: `Binary/${binaryId}`,
                },
            },
        ],
    }
}

function buildQuestionnaireResponse(launch: LaunchContext): QuestionnaireResponse {
    return {
        resourceType: 'QuestionnaireResponse',
        questionnaire: SYKMELDING_QUESTIONNAIRE_CANONICAL_URL,
        status: 'completed',
        subject: { reference: `Patient/${launch.patientId}` },
        encounter: { reference: `Encounter/${launch.encounterId}` },
        authored: new Date().toISOString(),
        author: launch.practitionerId ? { reference: `Practitioner/${launch.practitionerId}` } : undefined,
        item: [
            {
                linkId: 'hoveddiagnose',
                answer: [
                    {
                        valueCoding: {
                            system: 'urn:oid:2.16.578.1.12.4.1.1.7110',
                            code: 'Z09',
                            display: 'Etterundersøkelse etter annen behandling',
                        },
                    },
                ],
            },
            {
                linkId: 'aktivitet',
                item: [
                    {
                        linkId: 'aktivitet-type',
                        answer: [{ valueCoding: { code: 'AKTIVITET_IKKE_MULIG' } }],
                    },
                    { linkId: 'aktivitet-fom', answer: [{ valueDate: '2026-01-01' }] },
                    { linkId: 'aktivitet-tom', answer: [{ valueDate: '2026-01-14' }] },
                ],
            },
        ],
    }
}

/** Per bundle.md: `entry.request` uses `PUT` with the client-assigned sykmelding id. */
function buildBatchBundle(launch: LaunchContext, sykmeldingId: string): Bundle {
    const documentReference: DocumentReference = {
        ...buildInlineDocumentReference(launch),
        id: sykmeldingId,
        context: {
            encounter: [{ reference: `Encounter/${launch.encounterId}` }],
            related: [{ reference: `QuestionnaireResponse/${sykmeldingId}` }],
        },
    }
    const questionnaireResponse: QuestionnaireResponse = {
        ...buildQuestionnaireResponse(launch),
        id: sykmeldingId,
    }

    return {
        resourceType: 'Bundle',
        type: REQUIRED_BATCH_BUNDLE_TYPE,
        entry: [
            {
                fullUrl: `QuestionnaireResponse/${sykmeldingId}`,
                resource: questionnaireResponse,
                request: { method: 'PUT', url: `QuestionnaireResponse/${sykmeldingId}` },
            },
            {
                fullUrl: `DocumentReference/${sykmeldingId}`,
                resource: documentReference,
                request: { method: 'PUT', url: `DocumentReference/${sykmeldingId}` },
            },
        ],
    }
}

export const documentReferenceInlineWriteProbe: ResourceProbe = {
    id: 'document-reference-write-inline',
    label: 'Write DocumentReference with inline base64 PDF via idempotent PUT (mechanism 1)',
    required: true,
    async run(context: ProbeContext): Promise<ProbeOutcome> {
        const { fhir, launch } = context
        if (launch.patientId == null || launch.encounterId == null) {
            return skipped(
                documentReferenceInlineWriteProbe,
                'Launch context is missing a patient or encounter id, so a DocumentReference cannot be filed against a consultation.',
            )
        }

        const sykmeldingId = testId('docref-inline')
        const payload = { ...buildInlineDocumentReference(launch), id: sykmeldingId }
        const first = await fhir.update('DocumentReference', sykmeldingId, payload)

        if (!grantsWriteScope(launch, 'DocumentReference')) {
            return scopeEnforcementOutcome(
                documentReferenceInlineWriteProbe,
                first,
                'DocumentReference',
                launch,
                'PUT',
            )
        }

        const validations = upsertOutcomeValidations(first, 'DocumentReference', 'first')

        if (!first.ok) {
            return {
                probeId: documentReferenceInlineWriteProbe.id,
                label: documentReferenceInlineWriteProbe.label,
                exchangeId: first.exchange.id,
                validations,
            }
        }

        validations.push(testResourceNotice('DocumentReference', sykmeldingId))
        validations.push(
            ...validateDocumentReference(asTyped<DocumentReference>(first.body, 'DocumentReference'), {
                id: sykmeldingId,
                patientId: launch.patientId,
                encounterId: launch.encounterId,
                practitionerId: launch.practitionerId,
            }),
        )

        const second = await fhir.update('DocumentReference', sykmeldingId, payload)
        validations.push(...upsertOutcomeValidations(second, 'DocumentReference', 'second'))
        if (second.ok) {
            validations.push(idempotencyValidation(first, second, 'DocumentReference', sykmeldingId))
        }

        const readBack = await fhir.read('DocumentReference', sykmeldingId)
        if (!readBack.ok) {
            validations.push(
                validation(
                    `GET ${readBack.exchange.request.url} (round-trip read-back) failed with status ${readBack.status}. The server accepted the write but the resource cannot be read back.`,
                    'ERROR',
                    [hl7Refs.documentReference],
                ),
            )
        } else {
            validations.push(
                validation(
                    `Round-trip read-back succeeded: GET ${readBack.exchange.request.url} returned 200 OK`,
                    'OK',
                ),
            )
            validations.push(
                ...validateDocumentReference(asTyped<DocumentReference>(readBack.body, 'DocumentReference'), {
                    id: sykmeldingId,
                    patientId: launch.patientId,
                    encounterId: launch.encounterId,
                    practitionerId: launch.practitionerId,
                }),
            )
        }

        validations.push(
            ...(await searchableValidations(
                context,
                'DocumentReference',
                sykmeldingId,
                { subject: `Patient/${launch.patientId}` },
                '"subject" (GET [base]/DocumentReference?subject=Patient/{id})',
            )),
        )
        validations.push(
            ...(await searchableValidations(
                context,
                'DocumentReference',
                sykmeldingId,
                { encounter: `Encounter/${launch.encounterId}` },
                '"encounter" (GET [base]/DocumentReference?encounter=Encounter/{id})',
            )),
        )

        return {
            probeId: documentReferenceInlineWriteProbe.id,
            label: documentReferenceInlineWriteProbe.label,
            exchangeId: first.exchange.id,
            validations,
        }
    },
}

export const documentReferenceBinaryWriteProbe: ResourceProbe = {
    id: 'document-reference-write-binary',
    label: 'Write Binary then DocumentReference referencing it via idempotent PUT (mechanism 2)',
    required: true,
    async run(context: ProbeContext): Promise<ProbeOutcome> {
        const { fhir, launch } = context
        if (launch.patientId == null || launch.encounterId == null) {
            return skipped(
                documentReferenceBinaryWriteProbe,
                'Launch context is missing a patient or encounter id, so a DocumentReference cannot be filed against a consultation.',
            )
        }

        const sykmeldingId = testId('docref-binary')

        if (!grantsWriteScope(launch, 'DocumentReference')) {
            const response = await fhir.update('DocumentReference', sykmeldingId, {
                ...buildInlineDocumentReference(launch),
                id: sykmeldingId,
            })
            return scopeEnforcementOutcome(
                documentReferenceBinaryWriteProbe,
                response,
                'DocumentReference',
                launch,
                'PUT',
            )
        }

        const binaryResponse = await fhir.create('Binary', buildBinary())
        const validations = createOutcomeValidations(binaryResponse, 'Binary')
        const binaryId = extractCreatedId(binaryResponse)

        if (binaryId == null) {
            validations.push(
                validation(
                    'Could not determine the id of the created Binary, so the Binary-reference DocumentReference mechanism could not be tested.',
                    'ERROR',
                    [hl7Refs.binary],
                ),
            )
            return {
                probeId: documentReferenceBinaryWriteProbe.id,
                label: documentReferenceBinaryWriteProbe.label,
                exchangeId: binaryResponse.exchange.id,
                validations,
            }
        }
        validations.push(testResourceNotice('Binary', binaryId))

        const payload = { ...buildDocumentReferenceForBinary(launch, binaryId), id: sykmeldingId }
        const first = await fhir.update('DocumentReference', sykmeldingId, payload)
        validations.push(...upsertOutcomeValidations(first, 'DocumentReference', 'first'))

        if (!first.ok) {
            return {
                probeId: documentReferenceBinaryWriteProbe.id,
                label: documentReferenceBinaryWriteProbe.label,
                exchangeId: first.exchange.id,
                validations,
            }
        }
        validations.push(testResourceNotice('DocumentReference', sykmeldingId))
        validations.push(
            ...validateDocumentReference(asTyped<DocumentReference>(first.body, 'DocumentReference'), {
                id: sykmeldingId,
                patientId: launch.patientId,
                encounterId: launch.encounterId,
                practitionerId: launch.practitionerId,
            }),
        )

        const second = await fhir.update('DocumentReference', sykmeldingId, payload)
        validations.push(...upsertOutcomeValidations(second, 'DocumentReference', 'second'))
        if (second.ok) {
            validations.push(idempotencyValidation(first, second, 'DocumentReference', sykmeldingId))
        }

        const readBack = await fhir.read('DocumentReference', sykmeldingId)
        if (!readBack.ok) {
            validations.push(
                validation(
                    `GET ${readBack.exchange.request.url} (round-trip read-back) failed with status ${readBack.status}.`,
                    'ERROR',
                    [hl7Refs.documentReference],
                ),
            )
        } else {
            const readDoc = asTyped<DocumentReference>(readBack.body, 'DocumentReference')
            const url = readDoc?.content?.[0]?.attachment.url
            if (url != null && url.includes(binaryId)) {
                validations.push(
                    validation(
                        `Round-trip read-back preserved the Binary reference: content[0].attachment.url = "${url}"`,
                        'OK',
                    ),
                )
            } else {
                validations.push(
                    validation(
                        `Round-trip read-back did not preserve the Binary reference; content[0].attachment.url was "${url ?? 'missing'}", expected it to contain "${binaryId}". The server may have inlined or dropped the reference.`,
                        'ERROR',
                        [hl7Refs.documentReference],
                    ),
                )
            }
        }

        return {
            probeId: documentReferenceBinaryWriteProbe.id,
            label: documentReferenceBinaryWriteProbe.label,
            exchangeId: first.exchange.id,
            validations,
        }
    },
}

export const binaryWriteProbe: ResourceProbe = {
    id: 'binary-write',
    label: 'Write Binary via FHIR-JSON POST and raw-body POST',
    required: true,
    async run({ fhir, launch }: ProbeContext): Promise<ProbeOutcome> {
        const jsonResponse = await fhir.create('Binary', buildBinary())

        if (!grantsWriteScope(launch, 'Binary')) {
            return scopeEnforcementOutcome(binaryWriteProbe, jsonResponse, 'Binary', launch)
        }

        const jsonOutcome = await binaryMechanismValidations(
            fhir,
            jsonResponse,
            'FHIR-JSON POST (resourceType: "Binary")',
        )

        const rawResponse = await fhir.createBinaryRaw('application/pdf', TEST_PDF_BYTES)
        const rawOutcome = await binaryMechanismValidations(
            fhir,
            rawResponse,
            'raw-body POST (HTTP Content-Type: application/pdf)',
        )

        const validations = [...jsonOutcome.validations, ...rawOutcome.validations]

        if (jsonOutcome.succeeded && rawOutcome.succeeded) {
            validations.push(
                validation(
                    'Both Binary upload mechanisms (FHIR-JSON POST and raw-body POST) succeeded. Nav can write a Binary using either mechanism.',
                    'OK',
                    [navRefs.binary],
                ),
            )
        } else if (jsonOutcome.succeeded || rawOutcome.succeeded) {
            const working = jsonOutcome.succeeded ? 'FHIR-JSON POST' : 'raw-body POST'
            const failing = jsonOutcome.succeeded ? 'raw-body POST' : 'FHIR-JSON POST'
            validations.push(
                validation(
                    `Only the ${working} Binary upload mechanism succeeded; the ${failing} mechanism failed. Nav requires Binary write support (nav-requirements.md, "Må") but does not mandate a specific upload mechanism, so this alone is not fatal. The vendor should confirm their integration with Nav will use ${working}.`,
                    'WARNING',
                    [navRefs.binary],
                ),
            )
        } else {
            validations.push(
                validation(
                    'Both Binary upload mechanisms (FHIR-JSON POST and raw-body POST) failed. Nav requires Binary write support (nav-requirements.md, "Må"); a server supporting neither mechanism cannot receive the sykmelding PDF via Binary at all.',
                    'ERROR',
                    [navRefs.binary],
                ),
            )
        }

        return {
            probeId: binaryWriteProbe.id,
            label: binaryWriteProbe.label,
            exchangeId: jsonResponse.exchange.id,
            validations,
        }
    },
}

export const questionnaireResponseWriteProbe: ResourceProbe = {
    id: 'questionnaire-response-write',
    label: 'Write QuestionnaireResponse via idempotent PUT (optional per ADR01)',
    required: false,
    async run(context: ProbeContext): Promise<ProbeOutcome> {
        const { fhir, launch } = context
        if (launch.patientId == null || launch.encounterId == null) {
            return skipped(
                questionnaireResponseWriteProbe,
                'Launch context is missing a patient or encounter id, so a QuestionnaireResponse cannot be linked to a consultation.',
            )
        }

        const sykmeldingId = testId('qr')
        const payload = { ...buildQuestionnaireResponse(launch), id: sykmeldingId }
        const first = await fhir.update('QuestionnaireResponse', sykmeldingId, payload)

        if (!grantsWriteScope(launch, 'QuestionnaireResponse')) {
            return scopeEnforcementOutcome(
                questionnaireResponseWriteProbe,
                first,
                'QuestionnaireResponse',
                launch,
                'PUT',
            )
        }

        const validations = upsertOutcomeValidations(first, 'QuestionnaireResponse', 'first')

        if (!first.ok) {
            return {
                probeId: questionnaireResponseWriteProbe.id,
                label: questionnaireResponseWriteProbe.label,
                exchangeId: first.exchange.id,
                validations,
            }
        }

        validations.push(testResourceNotice('QuestionnaireResponse', sykmeldingId))
        validations.push(
            ...validateQuestionnaireResponse(
                asTyped<QuestionnaireResponse>(first.body, 'QuestionnaireResponse'),
                {
                    id: sykmeldingId,
                    patientId: launch.patientId,
                    encounterId: launch.encounterId,
                    practitionerId: launch.practitionerId,
                },
            ),
        )

        const second = await fhir.update('QuestionnaireResponse', sykmeldingId, payload)
        validations.push(...upsertOutcomeValidations(second, 'QuestionnaireResponse', 'second'))
        if (second.ok) {
            validations.push(idempotencyValidation(first, second, 'QuestionnaireResponse', sykmeldingId))
        }

        validations.push(
            ...(await searchableValidations(
                context,
                'QuestionnaireResponse',
                sykmeldingId,
                { subject: `Patient/${launch.patientId}` },
                '"subject" (GET [base]/QuestionnaireResponse?subject=Patient/{id})',
            )),
        )
        validations.push(
            ...(await searchableValidations(
                context,
                'QuestionnaireResponse',
                sykmeldingId,
                { encounter: `Encounter/${launch.encounterId}` },
                '"encounter" (GET [base]/QuestionnaireResponse?encounter=Encounter/{id})',
            )),
        )

        return {
            probeId: questionnaireResponseWriteProbe.id,
            label: questionnaireResponseWriteProbe.label,
            exchangeId: first.exchange.id,
            validations,
        }
    },
}

export const bundleBatchWriteProbe: ResourceProbe = {
    id: 'bundle-batch-write',
    label: 'Submit a batch Bundle with DocumentReference + QuestionnaireResponse (optional per ADR01)',
    required: false,
    async run({ fhir, launch }: ProbeContext): Promise<ProbeOutcome> {
        if (launch.patientId == null || launch.encounterId == null) {
            return skipped(
                bundleBatchWriteProbe,
                'Launch context is missing a patient or encounter id, so a batch Bundle cannot be constructed.',
            )
        }

        const hasDocRefScope = grantsWriteScope(launch, 'DocumentReference')
        const hasQrScope = grantsWriteScope(launch, 'QuestionnaireResponse')
        if (!hasDocRefScope || !hasQrScope) {
            const missing = [
                !hasDocRefScope ? 'DocumentReference' : null,
                !hasQrScope ? 'QuestionnaireResponse' : null,
            ]
                .filter((value): value is string => value != null)
                .join(' and ')
            return skipped(
                bundleBatchWriteProbe,
                `Granted scopes (${grantedScopesText(launch)}) do not include write access to ${missing}, required for both entries in the batch. Scope enforcement for each resource type individually is already covered by the standalone write probes.`,
            )
        }

        const sykmeldingId = testId('batch')
        const bundle = buildBatchBundle(launch, sykmeldingId)

        const validations = validateBatchBundleRequest(bundle)
        const response = await fhir.submitBundle(bundle)
        const url = response.exchange.request.url

        if (!response.ok) {
            const outcomeSummary = operationOutcomeSummary(response.body)
            validations.push(
                validation(
                    `POST ${url} (batch Bundle) failed with status ${response.status}. ${outcomeSummary ? `Server returned: ${outcomeSummary}` : 'No OperationOutcome was returned.'}`,
                    'ERROR',
                    [hl7Refs.bundleTransaction],
                ),
            )
            return {
                probeId: bundleBatchWriteProbe.id,
                label: bundleBatchWriteProbe.label,
                exchangeId: response.exchange.id,
                validations,
            }
        }

        validations.push(testResourceNotice('QuestionnaireResponse', sykmeldingId))
        validations.push(testResourceNotice('DocumentReference', sykmeldingId))
        validations.push(
            ...validateBatchBundleResponse(
                asTyped<Bundle>(response.body, 'Bundle'),
                bundle.entry?.length ?? 0,
            ),
        )

        return {
            probeId: bundleBatchWriteProbe.id,
            label: bundleBatchWriteProbe.label,
            exchangeId: response.exchange.id,
            validations,
        }
    },
}

export const writeProbes: ResourceProbe[] = [
    documentReferenceInlineWriteProbe,
    documentReferenceBinaryWriteProbe,
    binaryWriteProbe,
    questionnaireResponseWriteProbe,
    bundleBatchWriteProbe,
]

export function runWriteProbes(context: ProbeContext): Promise<ProbeOutcome[]> {
    return runProbes(writeProbes, context)
}

export const testHelpers = {
    buildInlineDocumentReference,
    buildBinary,
    buildDocumentReferenceForBinary,
    buildQuestionnaireResponse,
    buildBatchBundle,
    grantsWriteScope,
    extractCreatedId,
}
