import { randomUUID } from 'node:crypto'

import type { RecordedResponse } from '#core/http/smart-http-client'
import type { LaunchContext } from '#core/smart/types'
import { hl7Refs } from '#validation/common-refs'
import {
    runProbes,
    skipped,
    type ProbeContext,
    type ProbeOutcome,
    type ResourceProbe,
} from '#validation/fhir/probe'
import { parseScope } from '#validation/smart/scopes'
import { validation, type Validation } from '#validation/validation'
import type { Binary, Bundle, DocumentReference, OperationOutcome, QuestionnaireResponse } from 'fhir/r4'

import { validateBinary } from './resources/binary'
import {
    REQUIRED_BATCH_BUNDLE_TYPE,
    validateBatchBundleRequest,
    validateBatchBundleResponse,
} from './resources/bundle'
import {
    SYKMELDING_DOCUMENT_TYPE_CODE,
    SYKMELDING_DOCUMENT_TYPE_SYSTEM,
    validateDocumentReference,
} from './resources/document-reference'
import {
    SYKMELDING_QUESTIONNAIRE_CANONICAL_URL,
    validateQuestionnaireResponse,
} from './resources/questionnaire-response'

/**
 * Write probes are the only probes in this app that mutate the vendor's EHR: every successful
 * run leaves a test resource behind. Each probe's findings say exactly what was created and with
 * which id, so the vendor can find and delete it afterwards.
 *
 * `FhirClient.create` is a `POST` (server-assigned id). Nav's real write-back
 * (see `bundle.md` / ADR01) instead performs a `PUT /<type>/<sykmelding-id>` upsert with a
 * client-assigned id, which lets `DocumentReference.context.related` point at a
 * `QuestionnaireResponse` id that is known before either resource is written. `FhirClient` does
 * not expose an `update`/`PUT` method, so the standalone write probes below exercise the
 * POST-create path instead; only `bundleBatchWriteProbe` exercises the true PUT-upsert semantics,
 * because a `batch` Bundle carries `request.method` as data rather than requiring a client
 * method. See the task summary for this gap.
 */

const TEST_PDF_BASE64 = Buffer.from(
    '%PDF-1.4\n% Minimal placeholder document generated by the Nav SMART on FHIR validator.\n',
).toString('base64')

function testId(kind: string): string {
    return `smart-on-fhir-validator-${kind}-${randomUUID()}`
}

function grantedScopesText(launch: LaunchContext): string {
    return launch.grantedScopes.length > 0 ? launch.grantedScopes.join(', ') : 'none'
}

/**
 * A granted scope permits writing `resourceType` when it is a clinical scope for the resource
 * itself or `*`, whose normalized CRUDS permission includes create, update or delete. Uses the
 * shared SMART scope parser so v1 (`write`) and v2 (`cud...`/`cruds`) forms are both understood
 * consistently with the rest of the app.
 */
function grantsWriteScope(launch: LaunchContext, resourceType: string): boolean {
    return launch.grantedScopes.some((raw) => {
        const scope = parseScope(raw)
        if (scope.kind !== 'clinical') return false
        if (scope.resource !== '*' && scope.resource !== resourceType) return false
        return /[cud]/.test(scope.cruds)
    })
}

function asRecord(body: unknown): Record<string, unknown> | null {
    return body != null && typeof body === 'object' ? (body as Record<string, unknown>) : null
}

function asTyped<T extends { resourceType: string }>(
    body: unknown,
    resourceType: T['resourceType'],
): T | null {
    const record = asRecord(body)
    return record?.resourceType === resourceType ? (record as unknown as T) : null
}

function operationOutcomeSummary(body: unknown): string | null {
    const outcome = asTyped<OperationOutcome>(body, 'OperationOutcome')
    if (!outcome?.issue) return null
    return outcome.issue.map((issue) => issue.diagnostics ?? issue.details?.text ?? issue.code).join('; ')
}

function extractCreatedId(response: RecordedResponse): string | null {
    const bodyId = asRecord(response.body)?.id
    if (typeof bodyId === 'string' && bodyId.length > 0) return bodyId

    const location = response.headers.get('Location') ?? response.headers.get('Content-Location')
    if (!location) return null

    const match = /\/([^/?]+?)(?:\/_history\/[^/?]+)?\/?(?:\?.*)?$/.exec(location)
    return match?.[1] ?? null
}

/** Validates the plain HTTP shape of a create response: status code and Location header. */
function createOutcomeValidations(response: RecordedResponse, resourceType: string): Validation[] {
    const validations: Validation[] = []
    const url = response.exchange.request.url

    if (response.status === 201) {
        validations.push(validation(`POST ${url} correctly returned 201 Created`, 'OK'))
    } else if (response.status === 200) {
        validations.push(
            validation(
                `POST ${url} returned 200 OK instead of 201 Created for a new ${resourceType}. FHIR R4 requires a successful create to return 201.`,
                'WARNING',
                { hl7: hl7Refs.fhirHttpCreate },
            ),
        )
    } else {
        const outcomeSummary = operationOutcomeSummary(response.body)
        const transport =
            response.status === 0 ? ` (transport failure: ${response.exchange.error ?? 'unknown'})` : ''
        validations.push(
            validation(
                `POST ${url} failed to create the ${resourceType} with status ${response.status}${transport}. ${outcomeSummary ? `Server returned: ${outcomeSummary}` : 'No OperationOutcome was returned to explain the failure.'}`,
                'ERROR',
                { hl7: hl7Refs.fhirHttpCreate },
            ),
        )
        return validations
    }

    const location = response.headers.get('Location') ?? response.headers.get('Content-Location')
    if (!location) {
        validations.push(
            validation(
                `POST ${url} did not include a Location or Content-Location header pointing at the created ${resourceType}`,
                'WARNING',
                { hl7: hl7Refs.fhirHttpCreate },
            ),
        )
    } else {
        validations.push(validation(`Response included a Location header: "${location}"`, 'OK'))
    }

    return validations
}

/**
 * Treats a 403 as the correct outcome when the write scope was never granted, per the task's
 * scope-enforcement rule: a vendor that rejects an unauthorised write is behaving correctly, not
 * failing the check.
 */
function scopeEnforcementOutcome(
    probe: ResourceProbe,
    response: RecordedResponse,
    resourceType: string,
    launch: LaunchContext,
): ProbeOutcome {
    const url = response.exchange.request.url
    const validations: Validation[] = []

    if (response.status === 403) {
        validations.push(
            validation(
                `No write scope for ${resourceType} was granted (granted scopes: ${grantedScopesText(launch)}). POST ${url} was correctly rejected with 403 Forbidden — this is the expected, secure behaviour for a write attempted outside the granted scopes.`,
                'OK',
                { hl7: hl7Refs.smartLaunch },
            ),
        )
    } else if (response.ok) {
        validations.push(
            validation(
                `No write scope for ${resourceType} was granted (granted scopes: ${grantedScopesText(launch)}), yet POST ${url} succeeded with status ${response.status}. A SMART-conformant server must enforce granted scopes and reject writes outside them with 403 Forbidden.`,
                'ERROR',
                { hl7: hl7Refs.smartLaunch },
            ),
        )
    } else {
        validations.push(
            validation(
                `No write scope for ${resourceType} was granted (granted scopes: ${grantedScopesText(launch)}). POST ${url} was rejected with status ${response.status} rather than 403 Forbidden. 403 is the status a SMART server should use to signal insufficient authorization for an otherwise well-formed request.`,
                'WARNING',
                { hl7: hl7Refs.smartLaunch },
            ),
        )
    }

    return { probeId: probe.id, label: probe.label, exchangeId: response.exchange.id, validations }
}

function testResourceNotice(resourceType: string, id: string): Validation {
    return validation(
        `Created a test ${resourceType} in the vendor's EHR with id "${id}". This is a real record written to their system by this validator — please delete/clean up "${resourceType}/${id}" after reviewing this report.`,
        'INFO',
    )
}

function containsResource(bundle: Bundle | null, resourceType: string, id: string): boolean {
    if (bundle == null) return false
    return (bundle.entry ?? []).some((entry) => {
        const resource = entry.resource as { resourceType?: string; id?: string } | undefined
        return resource?.resourceType === resourceType && resource.id === id
    })
}

/** Verifies `resourceType` can be found from launch context alone, per the task's core requirement. */
async function searchableValidations(
    context: ProbeContext,
    resourceType: string,
    createdId: string,
    params: Record<string, string>,
    paramDescription: string,
): Promise<Validation[]> {
    const response = await context.fhir.search(resourceType, params)
    const url = response.exchange.request.url
    const validations: Validation[] = []

    if (!response.ok) {
        validations.push(
            validation(
                `GET ${url} failed with status ${response.status}. A written ${resourceType} must be findable by ${paramDescription} alone.`,
                'ERROR',
                { hl7: hl7Refs.fhirHttpSearch },
            ),
        )
        return validations
    }

    const bundle = asTyped<Bundle>(response.body, 'Bundle')
    if (bundle == null) {
        validations.push(
            validation(`GET ${url} did not return a FHIR Bundle`, 'ERROR', { hl7: hl7Refs.fhirHttpSearch }),
        )
        return validations
    }

    if (bundle.type !== 'searchset') {
        validations.push(
            validation(
                `GET ${url} returned a Bundle of type "${bundle.type}", expected "searchset"`,
                'ERROR',
                { hl7: hl7Refs.search },
            ),
        )
    }

    if (containsResource(bundle, resourceType, createdId)) {
        validations.push(
            validation(
                `The created ${resourceType} was found via GET ${url} (searchable by ${paramDescription})`,
                'OK',
            ),
        )
    } else {
        validations.push(
            validation(
                `The created ${resourceType} ("${resourceType}/${createdId}") was NOT found via GET ${url}. It must be discoverable by ${paramDescription} alone so it can be located without a server-assigned id.`,
                'ERROR',
                { hl7: hl7Refs.documentReference },
            ),
        )
    }

    return validations
}

function buildInlineDocumentReference(launch: LaunchContext): DocumentReference {
    return {
        resourceType: 'DocumentReference',
        status: 'current',
        type: {
            coding: [
                {
                    system: SYKMELDING_DOCUMENT_TYPE_SYSTEM,
                    code: SYKMELDING_DOCUMENT_TYPE_CODE,
                    display: 'Sykmeldinger og trygdesaker',
                },
            ],
        },
        subject: { reference: `Patient/${launch.patientId}` },
        author: launch.practitionerId ? [{ reference: `Practitioner/${launch.practitionerId}` }] : undefined,
        date: new Date().toISOString(),
        description: 'Sykmelding write-back test document from the Nav SMART on FHIR validator',
        content: [
            {
                attachment: {
                    title: 'Sykmelding (test)',
                    language: 'NO-nb',
                    contentType: 'application/pdf',
                    data: TEST_PDF_BASE64,
                },
            },
        ],
        context: {
            encounter: [{ reference: `Encounter/${launch.encounterId}` }],
        },
    }
}

function buildBinary(): Binary {
    return { resourceType: 'Binary', contentType: 'application/pdf', data: TEST_PDF_BASE64 }
}

function buildDocumentReferenceForBinary(launch: LaunchContext, binaryId: string): DocumentReference {
    const doc = buildInlineDocumentReference(launch)
    return {
        ...doc,
        content: [
            {
                attachment: {
                    title: 'Sykmelding (test, Binary reference)',
                    language: 'NO-nb',
                    contentType: 'application/pdf',
                    url: `Binary/${binaryId}`,
                },
            },
        ],
    }
}

function buildQuestionnaireResponse(launch: LaunchContext): QuestionnaireResponse {
    return {
        resourceType: 'QuestionnaireResponse',
        questionnaire: SYKMELDING_QUESTIONNAIRE_CANONICAL_URL,
        status: 'completed',
        subject: { reference: `Patient/${launch.patientId}` },
        encounter: { reference: `Encounter/${launch.encounterId}` },
        authored: new Date().toISOString(),
        author: launch.practitionerId ? { reference: `Practitioner/${launch.practitionerId}` } : undefined,
        item: [
            {
                linkId: 'hoveddiagnose',
                answer: [
                    {
                        valueCoding: {
                            system: 'urn:oid:2.16.578.1.12.4.1.1.7110',
                            code: 'Z09',
                            display: 'Etterundersøkelse etter annen behandling',
                        },
                    },
                ],
            },
            {
                linkId: 'aktivitet',
                item: [
                    {
                        linkId: 'aktivitet-type',
                        answer: [{ valueCoding: { code: 'AKTIVITET_IKKE_MULIG' } }],
                    },
                    { linkId: 'aktivitet-fom', answer: [{ valueDate: '2026-01-01' }] },
                    { linkId: 'aktivitet-tom', answer: [{ valueDate: '2026-01-14' }] },
                ],
            },
        ],
    }
}

/** Per bundle.md: `entry.request` uses `PUT` with the client-assigned sykmelding id. */
function buildBatchBundle(launch: LaunchContext, sykmeldingId: string): Bundle {
    const documentReference: DocumentReference = {
        ...buildInlineDocumentReference(launch),
        id: sykmeldingId,
        context: {
            encounter: [{ reference: `Encounter/${launch.encounterId}` }],
            related: [{ reference: `QuestionnaireResponse/${sykmeldingId}` }],
        },
    }
    const questionnaireResponse: QuestionnaireResponse = {
        ...buildQuestionnaireResponse(launch),
        id: sykmeldingId,
    }

    return {
        resourceType: 'Bundle',
        type: REQUIRED_BATCH_BUNDLE_TYPE,
        entry: [
            {
                fullUrl: `QuestionnaireResponse/${sykmeldingId}`,
                resource: questionnaireResponse,
                request: { method: 'PUT', url: `QuestionnaireResponse/${sykmeldingId}` },
            },
            {
                fullUrl: `DocumentReference/${sykmeldingId}`,
                resource: documentReference,
                request: { method: 'PUT', url: `DocumentReference/${sykmeldingId}` },
            },
        ],
    }
}

export const documentReferenceInlineWriteProbe: ResourceProbe = {
    id: 'document-reference-write-inline',
    label: 'Write DocumentReference with inline base64 PDF (mechanism 1)',
    required: true,
    async run(context: ProbeContext): Promise<ProbeOutcome> {
        const { fhir, launch } = context
        if (launch.patientId == null || launch.encounterId == null) {
            return skipped(
                documentReferenceInlineWriteProbe,
                'Launch context is missing a patient or encounter id, so a DocumentReference cannot be filed against a consultation.',
            )
        }

        const payload = buildInlineDocumentReference(launch)
        const response = await fhir.create('DocumentReference', payload)

        if (!grantsWriteScope(launch, 'DocumentReference')) {
            return scopeEnforcementOutcome(
                documentReferenceInlineWriteProbe,
                response,
                'DocumentReference',
                launch,
            )
        }

        const validations = createOutcomeValidations(response, 'DocumentReference')
        const createdId = extractCreatedId(response)

        if (createdId == null) {
            validations.push(
                validation(
                    'Could not determine the id of the created DocumentReference from the response body or Location header, so round-trip and searchability could not be verified.',
                    'ERROR',
                    { hl7: hl7Refs.fhirHttpCreate },
                ),
            )
            return {
                probeId: documentReferenceInlineWriteProbe.id,
                label: documentReferenceInlineWriteProbe.label,
                exchangeId: response.exchange.id,
                validations,
            }
        }

        validations.push(testResourceNotice('DocumentReference', createdId))
        validations.push(
            ...validateDocumentReference(asTyped<DocumentReference>(response.body, 'DocumentReference'), {
                id: createdId,
                patientId: launch.patientId,
                encounterId: launch.encounterId,
                practitionerId: launch.practitionerId,
            }),
        )

        const readBack = await fhir.read('DocumentReference', createdId)
        if (!readBack.ok) {
            validations.push(
                validation(
                    `GET ${readBack.exchange.request.url} (round-trip read-back) failed with status ${readBack.status}. The server accepted the write but the resource cannot be read back.`,
                    'ERROR',
                    { hl7: hl7Refs.documentReference },
                ),
            )
        } else {
            validations.push(
                validation(
                    `Round-trip read-back succeeded: GET ${readBack.exchange.request.url} returned 200 OK`,
                    'OK',
                ),
            )
            validations.push(
                ...validateDocumentReference(asTyped<DocumentReference>(readBack.body, 'DocumentReference'), {
                    id: createdId,
                    patientId: launch.patientId,
                    encounterId: launch.encounterId,
                    practitionerId: launch.practitionerId,
                }),
            )
        }

        validations.push(
            ...(await searchableValidations(
                context,
                'DocumentReference',
                createdId,
                { subject: `Patient/${launch.patientId}` },
                '"subject" (GET [base]/DocumentReference?subject=Patient/{id})',
            )),
        )
        validations.push(
            ...(await searchableValidations(
                context,
                'DocumentReference',
                createdId,
                { encounter: `Encounter/${launch.encounterId}` },
                '"encounter" (GET [base]/DocumentReference?encounter=Encounter/{id})',
            )),
        )

        return {
            probeId: documentReferenceInlineWriteProbe.id,
            label: documentReferenceInlineWriteProbe.label,
            exchangeId: response.exchange.id,
            validations,
        }
    },
}

export const documentReferenceBinaryWriteProbe: ResourceProbe = {
    id: 'document-reference-write-binary',
    label: 'Write Binary then DocumentReference referencing it (mechanism 2)',
    required: true,
    async run(context: ProbeContext): Promise<ProbeOutcome> {
        const { fhir, launch } = context
        if (launch.patientId == null || launch.encounterId == null) {
            return skipped(
                documentReferenceBinaryWriteProbe,
                'Launch context is missing a patient or encounter id, so a DocumentReference cannot be filed against a consultation.',
            )
        }

        if (!grantsWriteScope(launch, 'DocumentReference')) {
            const response = await fhir.create('DocumentReference', buildInlineDocumentReference(launch))
            return scopeEnforcementOutcome(
                documentReferenceBinaryWriteProbe,
                response,
                'DocumentReference',
                launch,
            )
        }

        const binaryResponse = await fhir.create('Binary', buildBinary())
        const validations = createOutcomeValidations(binaryResponse, 'Binary')
        const binaryId = extractCreatedId(binaryResponse)

        if (binaryId == null) {
            validations.push(
                validation(
                    'Could not determine the id of the created Binary, so the Binary-reference DocumentReference mechanism could not be tested.',
                    'ERROR',
                    { hl7: hl7Refs.binary },
                ),
            )
            return {
                probeId: documentReferenceBinaryWriteProbe.id,
                label: documentReferenceBinaryWriteProbe.label,
                exchangeId: binaryResponse.exchange.id,
                validations,
            }
        }
        validations.push(testResourceNotice('Binary', binaryId))

        const docResponse = await fhir.create(
            'DocumentReference',
            buildDocumentReferenceForBinary(launch, binaryId),
        )
        validations.push(...createOutcomeValidations(docResponse, 'DocumentReference'))
        const docId = extractCreatedId(docResponse)

        if (docId == null) {
            validations.push(
                validation(
                    'Could not determine the id of the created DocumentReference, so round-trip could not be verified.',
                    'ERROR',
                    { hl7: hl7Refs.fhirHttpCreate },
                ),
            )
            return {
                probeId: documentReferenceBinaryWriteProbe.id,
                label: documentReferenceBinaryWriteProbe.label,
                exchangeId: docResponse.exchange.id,
                validations,
            }
        }
        validations.push(testResourceNotice('DocumentReference', docId))
        validations.push(
            ...validateDocumentReference(asTyped<DocumentReference>(docResponse.body, 'DocumentReference'), {
                id: docId,
                patientId: launch.patientId,
                encounterId: launch.encounterId,
                practitionerId: launch.practitionerId,
            }),
        )

        const readBack = await fhir.read('DocumentReference', docId)
        if (!readBack.ok) {
            validations.push(
                validation(
                    `GET ${readBack.exchange.request.url} (round-trip read-back) failed with status ${readBack.status}.`,
                    'ERROR',
                    { hl7: hl7Refs.documentReference },
                ),
            )
        } else {
            const readDoc = asTyped<DocumentReference>(readBack.body, 'DocumentReference')
            const url = readDoc?.content?.[0]?.attachment.url
            if (url != null && url.includes(binaryId)) {
                validations.push(
                    validation(
                        `Round-trip read-back preserved the Binary reference: content[0].attachment.url = "${url}"`,
                        'OK',
                    ),
                )
            } else {
                validations.push(
                    validation(
                        `Round-trip read-back did not preserve the Binary reference; content[0].attachment.url was "${url ?? 'missing'}", expected it to contain "${binaryId}". The server may have inlined or dropped the reference.`,
                        'ERROR',
                        { hl7: hl7Refs.documentReference },
                    ),
                )
            }
        }

        return {
            probeId: documentReferenceBinaryWriteProbe.id,
            label: documentReferenceBinaryWriteProbe.label,
            exchangeId: docResponse.exchange.id,
            validations,
        }
    },
}

export const binaryWriteProbe: ResourceProbe = {
    id: 'binary-write',
    label: 'Write Binary via FHIR-JSON POST',
    required: true,
    async run({ fhir, launch }: ProbeContext): Promise<ProbeOutcome> {
        const response = await fhir.create('Binary', buildBinary())

        if (!grantsWriteScope(launch, 'Binary')) {
            return scopeEnforcementOutcome(binaryWriteProbe, response, 'Binary', launch)
        }

        const validations = createOutcomeValidations(response, 'Binary')
        const createdId = extractCreatedId(response)

        if (createdId == null) {
            validations.push(
                validation(
                    'Could not determine the id of the created Binary from the response body or Location header, so round-trip could not be verified.',
                    'ERROR',
                    { hl7: hl7Refs.binary },
                ),
            )
            return {
                probeId: binaryWriteProbe.id,
                label: binaryWriteProbe.label,
                exchangeId: response.exchange.id,
                validations,
            }
        }

        validations.push(testResourceNotice('Binary', createdId))
        validations.push(
            ...validateBinary(asTyped<Binary>(response.body, 'Binary'), {
                id: createdId,
                contentType: 'application/pdf',
            }),
        )

        const readBack = await fhir.read('Binary', createdId)
        if (!readBack.ok) {
            validations.push(
                validation(
                    `GET ${readBack.exchange.request.url} (round-trip read-back) failed with status ${readBack.status}.`,
                    'ERROR',
                    { hl7: hl7Refs.binary },
                ),
            )
        } else {
            validations.push(
                validation(
                    `Round-trip read-back succeeded: GET ${readBack.exchange.request.url} returned 200 OK`,
                    'OK',
                ),
            )
            validations.push(
                ...validateBinary(asTyped<Binary>(readBack.body, 'Binary'), {
                    id: createdId,
                    contentType: 'application/pdf',
                }),
            )
        }

        return {
            probeId: binaryWriteProbe.id,
            label: binaryWriteProbe.label,
            exchangeId: response.exchange.id,
            validations,
        }
    },
}

export const questionnaireResponseWriteProbe: ResourceProbe = {
    id: 'questionnaire-response-write',
    label: 'Write QuestionnaireResponse with structured sykmelding data (optional per ADR01)',
    required: false,
    async run(context: ProbeContext): Promise<ProbeOutcome> {
        const { fhir, launch } = context
        if (launch.patientId == null || launch.encounterId == null) {
            return skipped(
                questionnaireResponseWriteProbe,
                'Launch context is missing a patient or encounter id, so a QuestionnaireResponse cannot be linked to a consultation.',
            )
        }

        const payload = buildQuestionnaireResponse(launch)
        const response = await fhir.create('QuestionnaireResponse', payload)

        if (!grantsWriteScope(launch, 'QuestionnaireResponse')) {
            return scopeEnforcementOutcome(
                questionnaireResponseWriteProbe,
                response,
                'QuestionnaireResponse',
                launch,
            )
        }

        const validations = createOutcomeValidations(response, 'QuestionnaireResponse')
        const createdId = extractCreatedId(response)

        if (createdId == null) {
            validations.push(
                validation(
                    'Could not determine the id of the created QuestionnaireResponse, so round-trip and searchability could not be verified.',
                    'ERROR',
                    { hl7: hl7Refs.questionnaireResponse },
                ),
            )
            return {
                probeId: questionnaireResponseWriteProbe.id,
                label: questionnaireResponseWriteProbe.label,
                exchangeId: response.exchange.id,
                validations,
            }
        }

        validations.push(testResourceNotice('QuestionnaireResponse', createdId))
        validations.push(
            ...validateQuestionnaireResponse(
                asTyped<QuestionnaireResponse>(response.body, 'QuestionnaireResponse'),
                {
                    id: createdId,
                    patientId: launch.patientId,
                    encounterId: launch.encounterId,
                    practitionerId: launch.practitionerId,
                },
            ),
        )

        validations.push(
            ...(await searchableValidations(
                context,
                'QuestionnaireResponse',
                createdId,
                { subject: `Patient/${launch.patientId}` },
                '"subject" (GET [base]/QuestionnaireResponse?subject=Patient/{id})',
            )),
        )
        validations.push(
            ...(await searchableValidations(
                context,
                'QuestionnaireResponse',
                createdId,
                { encounter: `Encounter/${launch.encounterId}` },
                '"encounter" (GET [base]/QuestionnaireResponse?encounter=Encounter/{id})',
            )),
        )

        return {
            probeId: questionnaireResponseWriteProbe.id,
            label: questionnaireResponseWriteProbe.label,
            exchangeId: response.exchange.id,
            validations,
        }
    },
}

export const bundleBatchWriteProbe: ResourceProbe = {
    id: 'bundle-batch-write',
    label: 'Submit a batch Bundle with DocumentReference + QuestionnaireResponse (optional per ADR01)',
    required: false,
    async run({ fhir, launch }: ProbeContext): Promise<ProbeOutcome> {
        if (launch.patientId == null || launch.encounterId == null) {
            return skipped(
                bundleBatchWriteProbe,
                'Launch context is missing a patient or encounter id, so a batch Bundle cannot be constructed.',
            )
        }

        const hasDocRefScope = grantsWriteScope(launch, 'DocumentReference')
        const hasQrScope = grantsWriteScope(launch, 'QuestionnaireResponse')
        if (!hasDocRefScope || !hasQrScope) {
            const missing = [
                !hasDocRefScope ? 'DocumentReference' : null,
                !hasQrScope ? 'QuestionnaireResponse' : null,
            ]
                .filter((value): value is string => value != null)
                .join(' and ')
            return skipped(
                bundleBatchWriteProbe,
                `Granted scopes (${grantedScopesText(launch)}) do not include write access to ${missing}, required for both entries in the batch. Scope enforcement for each resource type individually is already covered by the standalone write probes.`,
            )
        }

        const sykmeldingId = testId('batch')
        const bundle = buildBatchBundle(launch, sykmeldingId)

        const validations = validateBatchBundleRequest(bundle)
        const response = await fhir.submitBundle(bundle)
        const url = response.exchange.request.url

        if (!response.ok) {
            const outcomeSummary = operationOutcomeSummary(response.body)
            validations.push(
                validation(
                    `POST ${url} (batch Bundle) failed with status ${response.status}. ${outcomeSummary ? `Server returned: ${outcomeSummary}` : 'No OperationOutcome was returned.'}`,
                    'ERROR',
                    { hl7: hl7Refs.bundleTransaction },
                ),
            )
            return {
                probeId: bundleBatchWriteProbe.id,
                label: bundleBatchWriteProbe.label,
                exchangeId: response.exchange.id,
                validations,
            }
        }

        validations.push(testResourceNotice('QuestionnaireResponse', sykmeldingId))
        validations.push(testResourceNotice('DocumentReference', sykmeldingId))
        validations.push(
            ...validateBatchBundleResponse(
                asTyped<Bundle>(response.body, 'Bundle'),
                bundle.entry?.length ?? 0,
            ),
        )

        return {
            probeId: bundleBatchWriteProbe.id,
            label: bundleBatchWriteProbe.label,
            exchangeId: response.exchange.id,
            validations,
        }
    },
}

export const writeProbes: ResourceProbe[] = [
    documentReferenceInlineWriteProbe,
    documentReferenceBinaryWriteProbe,
    binaryWriteProbe,
    questionnaireResponseWriteProbe,
    bundleBatchWriteProbe,
]

export function runWriteProbes(context: ProbeContext): Promise<ProbeOutcome[]> {
    return runProbes(writeProbes, context)
}

/** Exported for unit testing without going through the full probe pipeline. */
export const testHelpers = {
    buildInlineDocumentReference,
    buildBinary,
    buildDocumentReferenceForBinary,
    buildQuestionnaireResponse,
    buildBatchBundle,
    grantsWriteScope,
    extractCreatedId,
}
