apiVersion: aiven.io/v1alpha1
kind: Valkey
metadata:
  labels:
    app: {{ app }}
    team: {{ team }}
  name: valkey-{{ team }}-{{ app }}
  namespace: {{ namespace }}
spec:
  plan: startup-4
  project: {{ valkeyProject }}
