/**
 * PKCE (RFC 7636) and OAuth `state`: per-launch secrets generated by this app.
 */

import { createHash, randomBytes } from 'node:crypto'

/** RFC 7636 §4.1: the unreserved character set a code verifier may use. */
const UNRESERVED_CHARACTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~'

/** RFC 7636 §4.1: verifiers must be 43-128 characters. Use the maximum for the most entropy. */
const CODE_VERIFIER_LENGTH = 128

const OAUTH_STATE_BYTES = 32

export type PkcePair = {
    codeVerifier: string
    codeChallenge: string
    method: 'S256'
}

export function createPkcePair(): PkcePair {
    const codeVerifier = randomUnreservedString(CODE_VERIFIER_LENGTH)

    return { codeVerifier, codeChallenge: computeCodeChallenge(codeVerifier), method: 'S256' }
}

/** RFC 7636 §4.2: `BASE64URL-ENCODE(SHA256(ASCII(code_verifier)))`. */
export function computeCodeChallenge(codeVerifier: string): string {
    return createHash('sha256').update(codeVerifier, 'ascii').digest('base64url')
}

/** An opaque, unguessable value for the OAuth `state` parameter. */
export function createOauthState(): string {
    return randomBytes(OAUTH_STATE_BYTES).toString('base64url')
}

function randomUnreservedString(length: number): string {
    const bytes = randomBytes(length)

    return Array.from(bytes, (byte) =>
        UNRESERVED_CHARACTERS.charAt(byte % UNRESERVED_CHARACTERS.length),
    ).join('')
}
