name: Build & Deploy
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".dockerignore"

env:
  IMAGE: europe-north1-docker.pkg.dev/${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}/helseopplysninger/${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn tsc
      - run: yarn build

      - name: Setter tag-navn for deploy
        run: echo "TAG=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          tag: ${{ env.TAG }}
          team: helseopplysninger
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
      id-token: write
    environment: dev-gcp:helseopplysninger
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/app.yaml
          VARS: .nais/dev-gcp.json
          IMAGE: ${{ needs.build.outputs.image }}
