name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.gitignore'

env:
  IMAGE: europe-north1-docker.pkg.dev/${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}/helseopplysninger/${{ github.event.repository.name }}

jobs:
  verify:
    uses: ./.github/workflows/ci.yml

  build:
    needs: [verify]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn build

      - name: Set deploy tag
        run: echo "TAG=$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          tag: ${{ env.TAG }}
          team: helseopplysninger
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-dev:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    environment: dev-gcp:helseopplysninger
    steps:
      - uses: actions/checkout@v7
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/app.yaml
          VARS: .nais/dev-gcp.json
          IMAGE: ${{ needs.build.outputs.image }}
