name: Deploy Valkey

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/deploy-valkey.yml
      - .nais/nais-dev-valkey.yaml
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy-valkey-dev:
    name: Deploy Valkey to dev-gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-dev-valkey.yaml
